name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Upgrade python tooling
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Install lint dependencies
      run: python -m pip install --upgrade mypy
    - name: Lint
      run: python -m mypy -p linehaul
    - name: Install test dependencies
      run: python -m pip install pytest pretend hypothesis pyaml
    - name: Test
      run: python -m pytest test_functions.py tests/unit
